name: Close Stale Issues & PRs

on:
  schedule:
    - cron: "0 0 * * *" # ูููููุง ูู ููุชุตู ุงูููู

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Issues
          stale-issue-message: "โฐ ูุฐู ุงููุดููุฉ ูู ูุชู ุงูุชูุงุนู ูุนูุง ููุฐ ูุชุฑุฉ. ุณูุชู ุฅุบูุงููุง ุชููุงุฆููุง ุฎูุงู 7 ุฃูุงู ุฅุฐุง ูู ููู ููุงู ูุดุงุท."
          close-issue-message: "๐ ุชู ุฅุบูุงู ูุฐู ุงููุดููุฉ ุชููุงุฆููุง ุจุณุจุจ ุนุฏู ุงููุดุงุท."
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: "stale"
          exempt-issue-labels: "pinned,security,enhancement"
          # Pull Requests
          stale-pr-message: "โฐ ูุฐุง ุงูู PR ูู ูุชู ุงูุชูุงุนู ูุนู ููุฐ ูุชุฑุฉ. ุณูุชู ุฅุบูุงูู ุชููุงุฆููุง ุฎูุงู 7 ุฃูุงู ุฅุฐุง ูู ููู ููุงู ูุดุงุท."
          close-pr-message: "๐ ุชู ุฅุบูุงู ูุฐุง ุงูู PR ุชููุงุฆููุง ุจุณุจุจ ุนุฏู ุงููุดุงุท."
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-label: "stale"
          exempt-pr-labels: "pinned,security"
